export const countries = [
  { name: 'Afghanistan', code: '+93', flag: 'af' },
  { name: 'Aland Islands', code: '+358', flag: 'ax' },
  { name: 'Albania', code: '+355', flag: 'al' },
  { name: 'Algeria', code: '+213', flag: 'dz' },
  { name: 'American Samoa', code: '+1684', flag: 'as' },
  { name: 'Andorra', code: '+376', flag: 'ad' },
  { name: 'Angola', code: '+244', flag: 'ao' },
  { name: 'Anguilla', code: '+1264', flag: 'ai' },
  { name: 'Antarctica', code: '+672', flag: 'aq' },
  { name: 'Antigua and Barbuda', code: '+1268', flag: 'ag' },
  { name: 'Argentina', code: '+54', flag: 'ar' },
  { name: 'Armenia', code: '+374', flag: 'am' },
  { name: 'Aruba', code: '+297', flag: 'aw' },
  { name: 'Australia', code: '+61', flag: 'au' },
  { name: 'Austria', code: '+43', flag: 'at' },
  { name: 'Azerbaijan', code: '+994', flag: 'az' },
  { name: 'Bahamas', code: '+1242', flag: 'bs' },
  { name: 'Bahrain', code: '+973', flag: 'bh' },
  { name: 'Bangladesh', code: '+880', flag: 'bd' },
  { name: 'Barbados', code: '+1246', flag: 'bb' },
  { name: 'Belarus', code: '+375', flag: 'by' },
  { name: 'Belgium', code: '+32', flag: 'be' },
  { name: 'Belize', code: '+501', flag: 'bz' },
  { name: 'Benin', code: '+229', flag: 'bj' },
  { name: 'Bermuda', code: '+1441', flag: 'bm' },
  { name: 'Bhutan', code: '+975', flag: 'bt' },
  { name: 'Bolivia', code: '+591', flag: 'bo' },
  { name: 'Bonaire, Sint Eustatius and Saba', code: '+599', flag: 'bq' },
  { name: 'Bosnia and Herzegovina', code: '+387', flag: 'ba' },
  { name: 'Botswana', code: '+267', flag: 'bw' },
  { name: 'Brazil', code: '+55', flag: 'br' },
  { name: 'British Indian Ocean Territory', code: '+246', flag: 'io' },
  { name: 'Brunei Darussalam', code: '+673', flag: 'bn' },
  { name: 'Bulgaria', code: '+359', flag: 'bg' },
  { name: 'Burkina Faso', code: '+226', flag: 'bf' },
  { name: 'Burundi', code: '+257', flag: 'bi' },
  { name: 'Cabo Verde', code: '+238', flag: 'cv' },
  { name: 'Cambodia', code: '+855', flag: 'kh' },
  { name: 'Cameroon', code: '+237', flag: 'cm' },
  { name: 'Canada', code: '+1', flag: 'ca' },
  { name: 'Cayman Islands', code: '+1345', flag: 'ky' },
  { name: 'Central African Republic', code: '+236', flag: 'cf' },
  { name: 'Chad', code: '+235', flag: 'td' },
  { name: 'Chile', code: '+56', flag: 'cl' },
  { name: 'China', code: '+86', flag: 'cn' },
  { name: 'Christmas Island', code: '+61', flag: 'cx' },
  { name: 'Cocos (Keeling) Islands', code: '+61', flag: 'cc' },
  { name: 'Colombia', code: '+57', flag: 'co' },
  { name: 'Comoros', code: '+269', flag: 'km' },
  { name: 'Congo', code: '+242', flag: 'cg' },
  { name: 'Congo (DRC)', code: '+243', flag: 'cd' },
  { name: 'Cook Islands', code: '+682', flag: 'ck' },
  { name: 'Costa Rica', code: '+506', flag: 'cr' },
  { name: 'Cote d\'Ivoire', code: '+225', flag: 'ci' },
  { name: 'Croatia', code: '+385', flag: 'hr' },
  { name: 'Cuba', code: '+53', flag: 'cu' },
  { name: 'Curacao', code: '+599', flag: 'cw' },
  { name: 'Cyprus', code: '+357', flag: 'cy' },
  { name: 'Czech Republic', code: '+420', flag: 'cz' },
  { name: 'Denmark', code: '+45', flag: 'dk' },
  { name: 'Djibouti', code: '+253', flag: 'dj' },
  { name: 'Dominica', code: '+1767', flag: 'dm' },
  { name: 'Dominican Republic', code: '+1', flag: 'do' },
  { name: 'Ecuador', code: '+593', flag: 'ec' },
  { name: 'Egypt', code: '+20', flag: 'eg' },
  { name: 'El Salvador', code: '+503', flag: 'sv' },
  { name: 'Equatorial Guinea', code: '+240', flag: 'gq' },
  { name: 'Eritrea', code: '+291', flag: 'er' },
  { name: 'Estonia', code: '+372', flag: 'ee' },
  { name: 'Eswatini', code: '+268', flag: 'sz' },
  { name: 'Ethiopia', code: '+251', flag: 'et' },
  { name: 'Falkland Islands (Malvinas)', code: '+500', flag: 'fk' },
  { name: 'Faroe Islands', code: '+298', flag: 'fo' },
  { name: 'Fiji', code: '+679', flag: 'fj' },
  { name: 'Finland', code: '+358', flag: 'fi' },
  { name: 'France', code: '+33', flag: 'fr' },
  { name: 'French Guiana', code: '+594', flag: 'gf' },
  { name: 'French Polynesia', code: '+689', flag: 'pf' },
  { name: 'Gabon', code: '+241', flag: 'ga' },
  { name: 'Gambia', code: '+220', flag: 'gm' },
  { name: 'Georgia', code: '+995', flag: 'ge' },
  { name: 'Germany', code: '+49', flag: 'de' },
  { name: 'Ghana', code: '+233', flag: 'gh' },
  { name: 'Gibraltar', code: '+350', flag: 'gi' },
  { name: 'Greece', code: '+30', flag: 'gr' },
  { name: 'Greenland', code: '+299', flag: 'gl' },
  { name: 'Grenada', code: '+1473', flag: 'gd' },
  { name: 'Guadeloupe', code: '+590', flag: 'gp' },
  { name: 'Guam', code: '+1671', flag: 'gu' },
  { name: 'Guatemala', code: '+502', flag: 'gt' },
  { name: 'Guernsey', code: '+44', flag: 'gg' },
  { name: 'Guinea', code: '+224', flag: 'gn' },
  { name: 'Guinea-Bissau', code: '+245', flag: 'gw' },
  { name: 'Guyana', code: '+592', flag: 'gy' },
  { name: 'Haiti', code: '+509', flag: 'ht' },
  { name: 'Honduras', code: '+504', flag: 'hn' },
  { name: 'Hong Kong', code: '+852', flag: 'hk' },
  { name: 'Hungary', code: '+36', flag: 'hu' },
  { name: 'Iceland', code: '+354', flag: 'is' },
  { name: 'India', code: '+91', flag: 'in' },
  { name: 'Indonesia', code: '+62', flag: 'id' },
  { name: 'Iran', code: '+98', flag: 'ir' },
  { name: 'Iraq', code: '+964', flag: 'iq' },
  { name: 'Ireland', code: '+353', flag: 'ie' },
  { name: 'Isle of Man', code: '+44', flag: 'im' },
  { name: 'Israel', code: '+972', flag: 'il' },
  { name: 'Italy', code: '+39', flag: 'it' },
  { name: 'Jamaica', code: '+1876', flag: 'jm' },
  { name: 'Japan', code: '+81', flag: 'jp' },
  { name: 'Jersey', code: '+44', flag: 'je' },
  { name: 'Jordan', code: '+962', flag: 'jo' },
  { name: 'Kazakhstan', code: '+7', flag: 'kz' },
  { name: 'Kenya', code: '+254', flag: 'ke' },
  { name: 'Kiribati', code: '+686', flag: 'ki' },
  { name: 'Kosovo', code: '+383', flag: 'xk' },
  { name: 'Kuwait', code: '+965', flag: 'kw' },
  { name: 'Kyrgyzstan', code: '+996', flag: 'kg' },
  { name: 'Laos', code: '+856', flag: 'la' },
  { name: 'Latvia', code: '+371', flag: 'lv' },
  { name: 'Lebanon', code: '+961', flag: 'lb' },
  { name: 'Lesotho', code: '+266', flag: 'ls' },
  { name: 'Liberia', code: '+231', flag: 'lr' },
  { name: 'Libya', code: '+218', flag: 'ly' },
  { name: 'Liechtenstein', code: '+423', flag: 'li' },
  { name: 'Lithuania', code: '+370', flag: 'lt' },
  { name: 'Luxembourg', code: '+352', flag: 'lu' },
  { name: 'Macao', code: '+853', flag: 'mo' },
  { name: 'Madagascar', code: '+261', flag: 'mg' },
  { name: 'Malawi', code: '+265', flag: 'mw' },
  { name: 'Malaysia', code: '+60', flag: 'my' },
  { name: 'Maldives', code: '+960', flag: 'mv' },
  { name: 'Mali', code: '+223', flag: 'ml' },
  { name: 'Malta', code: '+356', flag: 'mt' },
  { name: 'Marshall Islands', code: '+692', flag: 'mh' },
  { name: 'Martinique', code: '+596', flag: 'mq' },
  { name: 'Mauritania', code: '+222', flag: 'mr' },
  { name: 'Mauritius', code: '+230', flag: 'mu' },
  { name: 'Mayotte', code: '+262', flag: 'yt' },
  { name: 'Mexico', code: '+52', flag: 'mx' },
  { name: 'Micronesia', code: '+691', flag: 'fm' },
  { name: 'Moldova', code: '+373', flag: 'md' },
  { name: 'Monaco', code: '+377', flag: 'mc' },
  { name: 'Mongolia', code: '+976', flag: 'mn' },
  { name: 'Montenegro', code: '+382', flag: 'me' },
  { name: 'Montserrat', code: '+1664', flag: 'ms' },
  { name: 'Morocco', code: '+212', flag: 'ma' },
  { name: 'Mozambique', code: '+258', flag: 'mz' },
  { name: 'Myanmar', code: '+95', flag: 'mm' },
  { name: 'Namibia', code: '+264', flag: 'na' },
  { name: 'Nauru', code: '+674', flag: 'nr' },
  { name: 'Nepal', code: '+977', flag: 'np' },
  { name: 'Netherlands', code: '+31', flag: 'nl' },
  { name: 'New Caledonia', code: '+687', flag: 'nc' },
  { name: 'New Zealand', code: '+64', flag: 'nz' },
  { name: 'Nicaragua', code: '+505', flag: 'ni' },
  { name: 'Niger', code: '+227', flag: 'ne' },
  { name: 'Nigeria', code: '+234', flag: 'ng' },
  { name: 'Niue', code: '+683', flag: 'nu' },
  { name: 'Norfolk Island', code: '+672', flag: 'nf' },
  { name: 'North Korea', code: '+850', flag: 'kp' },
  { name: 'North Macedonia', code: '+389', flag: 'mk' },
  { name: 'Northern Mariana Islands', code: '+1670', flag: 'mp' },
  { name: 'Norway', code: '+47', flag: 'no' },
  { name: 'Oman', code: '+968', flag: 'om' },
  { name: 'Pakistan', code: '+92', flag: 'pk' },
  { name: 'Palau', code: '+680', flag: 'pw' },
  { name: 'Palestine', code: '+970', flag: 'ps' },
  { name: 'Panama', code: '+507', flag: 'pa' },
  { name: 'Papua New Guinea', code: '+675', flag: 'pg' },
  { name: 'Paraguay', code: '+595', flag: 'py' },
  { name: 'Peru', code: '+51', flag: 'pe' },
  { name: 'Philippines', code: '+63', flag: 'ph' },
  { name: 'Pitcairn', code: '+870', flag: 'pn' },
  { name: 'Poland', code: '+48', flag: 'pl' },
  { name: 'Portugal', code: '+351', flag: 'pt' },
  { name: 'Puerto Rico', code: '+1', flag: 'pr' },
  { name: 'Qatar', code: '+974', flag: 'qa' },
  { name: 'Reunion', code: '+262', flag: 're' },
  { name: 'Romania', code: '+40', flag: 'ro' },
  { name: 'Russia', code: '+7', flag: 'ru' },
  { name: 'Rwanda', code: '+250', flag: 'rw' },
  { name: 'Saint Barthelemy', code: '+590', flag: 'bl' },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', code: '+290', flag: 'sh' },
  { name: 'Saint Kitts and Nevis', code: '+1869', flag: 'kn' },
  { name: 'Saint Lucia', code: '+1758', flag: 'lc' },
  { name: 'Saint Martin (French part)', code: '+590', flag: 'mf' },
  { name: 'Saint Pierre and Miquelon', code: '+508', flag: 'pm' },
  { name: 'Saint Vincent and the Grenadines', code: '+1784', flag: 'vc' },
  { name: 'Samoa', code: '+685', flag: 'ws' },
  { name: 'San Marino', code: '+378', flag: 'sm' },
  { name: 'Sao Tome and Principe', code: '+239', flag: 'st' },
  { name: 'Saudi Arabia', code: '+966', flag: 'sa' },
  { name: 'Senegal', code: '+221', flag: 'sn' },
  { name: 'Serbia', code: '+381', flag: 'rs' },
  { name: 'Seychelles', code: '+248', flag: 'sc' },
  { name: 'Sierra Leone', code: '+232', flag: 'sl' },
  { name: 'Singapore', code: '+65', flag: 'sg' },
  { name: 'Sint Maarten (Dutch part)', code: '+1721', flag: 'sx' },
  { name: 'Slovakia', code: '+421', flag: 'sk' },
  { name: 'Slovenia', code: '+386', flag: 'si' },
  { name: 'Solomon Islands', code: '+677', flag: 'sb' },
  { name: 'Somalia', code: '+252', flag: 'so' },
  { name: 'South Africa', code: '+27', flag: 'za' },
  { name: 'South Korea', code: '+82', flag: 'kr' },
  { name: 'South Sudan', code: '+211', flag: 'ss' },
  { name: 'Spain', code: '+34', flag: 'es' },
  { name: 'Sri Lanka', code: '+94', flag: 'lk' },
  { name: 'Sudan', code: '+249', flag: 'sd' },
  { name: 'Suriname', code: '+597', flag: 'sr' },
  { name: 'Svalbard and Jan Mayen', code: '+47', flag: 'sj' },
  { name: 'Sweden', code: '+46', flag: 'se' },
  { name: 'Switzerland', code: '+41', flag: 'ch' },
  { name: 'Syria', code: '+963', flag: 'sy' },
  { name: 'Taiwan', code: '+886', flag: 'tw' },
  { name: 'Tajikistan', code: '+992', flag: 'tj' },
  { name: 'Tanzania', code: '+255', flag: 'tz' },
  { name: 'Thailand', code: '+66', flag: 'th' },
  { name: 'Timor-Leste', code: '+670', flag: 'tl' },
  { name: 'Togo', code: '+228', flag: 'tg' },
  { name: 'Tokelau', code: '+690', flag: 'tk' },
  { name: 'Tonga', code: '+676', flag: 'to' },
  { name: 'Trinidad and Tobago', code: '+1868', flag: 'tt' },
  { name: 'Tunisia', code: '+216', flag: 'tn' },
  { name: 'Turkey', code: '+90', flag: 'tr' },
  { name: 'Turkmenistan', code: '+993', flag: 'tm' },
  { name: 'Turks and Caicos Islands', code: '+1649', flag: 'tc' },
  { name: 'Tuvalu', code: '+688', flag: 'tv' },
  { name: 'Uganda', code: '+256', flag: 'ug' },
  { name: 'Ukraine', code: '+380', flag: 'ua' },
  { name: 'United Arab Emirates', code: '+971', flag: 'ae' },
  { name: 'United Kingdom', code: '+44', flag: 'gb' },
  { name: 'United States', code: '+1', flag: 'us' },
  { name: 'Uruguay', code: '+598', flag: 'uy' },
  { name: 'Uzbekistan', code: '+998', flag: 'uz' },
  { name: 'Vanuatu', code: '+678', flag: 'vu' },
  { name: 'Vatican City', code: '+39', flag: 'va' },
  { name: 'Venezuela', code: '+58', flag: 've' },
  { name: 'Vietnam', code: '+84', flag: 'vn' },
  { name: 'Virgin Islands (British)', code: '+1284', flag: 'vg' },
  { name: 'Virgin Islands (U.S.)', code: '+1340', flag: 'vi' },
  { name: 'Wallis and Futuna', code: '+681', flag: 'wf' },
  { name: 'Western Sahara', code: '+212', flag: 'eh' },
  { name: 'Yemen', code: '+967', flag: 'ye' },
  { name: 'Zambia', code: '+260', flag: 'zm' },
  { name: 'Zimbabwe', code: '+263', flag: 'zw' },
];
